name: Context Example

on: 
  workflow_dispatch
jobs:
  github_context:
    runs-on: ubuntu-latest
    steps:
      -name: Github Info Printing
      run: |
        echo 'Github Repository ${{github.repository}}'
        echo 'Github Repository ${{github.repository}}'
        echo 'Github Repository ${{github.repository}}'
        echo 'Github Repository ${{github.repository}}'
        echo 'Github Repository ${{github.repository}}'
        echo 'Github Repository ${{github.repository}}'
        echo 'Github Repository ${{github.repository}}'
        echo 'Github Repository ${{github.repository}}'
        echo 'Github Repository ${{github.repository}}'
        echo 'Github Repository ${{github.repository}}' 
    
